// Code generated by protoc-gen-gogo.
// source: plan.proto
// DO NOT EDIT!

/*
Package plan is a generated protocol buffer package.

It is generated from these files:

	plan.proto

It has these top-level messages:

	PlanPb
	SelectPb
	ContextPb
	SourcePb
	WherePb
	GroupByPb
	HavingPb
	OrderPb
	JoinMergePb
	JoinKeyPb
*/
package plan

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	_ "github.com/gogo/protobuf/gogoproto"

	rel "github.com/araddon/qlbridge/rel"

	expr "github.com/araddon/qlbridge/expr"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The generic Node, must be exactly one of these types
type PlanPb struct {
	Parallel         bool              `protobuf:"varint,1,req,name=parallel" json:"parallel"`
	Select           *SelectPb         `protobuf:"bytes,3,opt,name=select" json:"select,omitempty"`
	Source           *SourcePb         `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	Where            *WherePb          `protobuf:"bytes,5,opt,name=where" json:"where,omitempty"`
	Having           *HavingPb         `protobuf:"bytes,6,opt,name=having" json:"having,omitempty"`
	GroupBy          *GroupByPb        `protobuf:"bytes,7,opt,name=groupBy" json:"groupBy,omitempty"`
	Order            *OrderPb          `protobuf:"bytes,8,opt,name=order" json:"order,omitempty"`
	JoinMerge        *JoinMergePb      `protobuf:"bytes,9,opt,name=joinMerge" json:"joinMerge,omitempty"`
	JoinKey          *JoinKeyPb        `protobuf:"bytes,10,opt,name=joinKey" json:"joinKey,omitempty"`
	Projection       *rel.ProjectionPb `protobuf:"bytes,11,opt,name=projection" json:"projection,omitempty"`
	Children         []*PlanPb         `protobuf:"bytes,12,rep,name=children" json:"children,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlanPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PlanPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*PlanPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PlanPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Select Plan
type SelectPb struct {
	Select           *rel.SqlSelectPb `protobuf:"bytes,1,req,name=select" json:"select,omitempty"`
	Context          *ContextPb       `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SelectPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SelectPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*SelectPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SelectPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Context
type ContextPb struct {
	Schema           string `protobuf:"bytes,1,req,name=schema" json:"schema"`
	Id               uint64 `protobuf:"varint,2,req,name=id" json:"id"`
	Fingerprint      uint64 `protobuf:"varint,3,req,name=fingerprint" json:"fingerprint"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ContextPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ContextPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*ContextPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ContextPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Source Plan is a plan for single source of select query, of which
// many may exist (joins, sub-querys etc)
type SourcePb struct {
	// do we need group-by, join, partition key for routing purposes?
	NeedsHashableKey bool `protobuf:"varint,2,req,name=needsHashableKey" json:"needsHashableKey"`
	// Is this final projection or not?  non finals are partial-sub-query types
	Final bool `protobuf:"varint,3,req,name=final" json:"final"`
	// Is this plan complete as is?  skip remaining plan walk steps
	Complete         bool              `protobuf:"varint,4,req,name=complete" json:"complete"`
	Join             bool              `protobuf:"varint,5,req,name=join" json:"join"`
	SourceExec       bool              `protobuf:"varint,6,req,name=sourceExec" json:"sourceExec"`
	Custom           []byte            `protobuf:"bytes,7,opt,name=custom" json:"custom,omitempty"`
	SqlSource        *rel.SqlSourcePb  `protobuf:"bytes,8,opt,name=sqlSource" json:"sqlSource,omitempty"`
	Projection       *rel.ProjectionPb `protobuf:"bytes,9,opt,name=projection" json:"projection,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SourcePb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SourcePb) String() string            { _ = "STUB: not implemented"; return "" }
func (*SourcePb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SourcePb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Where Plan
type WherePb struct {
	Select           *rel.SqlSelectPb `protobuf:"bytes,1,opt,name=select" json:"select,omitempty"`
	Final            bool             `protobuf:"varint,2,req,name=final" json:"final"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *WherePb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *WherePb) String() string            { _ = "STUB: not implemented"; return "" }
func (*WherePb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*WherePb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Group By Plan
type GroupByPb struct {
	Select           *rel.SqlSelectPb `protobuf:"bytes,1,opt,name=select" json:"select,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GroupByPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GroupByPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*GroupByPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GroupByPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type HavingPb struct {
	Select           *rel.SqlSelectPb `protobuf:"bytes,1,opt,name=select" json:"select,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *HavingPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *HavingPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*HavingPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HavingPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type OrderPb struct {
	Select           *rel.SqlSelectPb `protobuf:"bytes,1,opt,name=select" json:"select,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *OrderPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *OrderPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*OrderPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*OrderPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type JoinMergePb struct {
	Having           *expr.NodePb `protobuf:"bytes,1,opt,name=having" json:"having,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *JoinMergePb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *JoinMergePb) String() string            { _ = "STUB: not implemented"; return "" }
func (*JoinMergePb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*JoinMergePb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type JoinKeyPb struct {
	Having           *expr.NodePb `protobuf:"bytes,1,opt,name=having" json:"having,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *JoinKeyPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *JoinKeyPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*JoinKeyPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*JoinKeyPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func init() {
	proto.RegisterType((*PlanPb)(nil), "plan.PlanPb")
	proto.RegisterType((*SelectPb)(nil), "plan.SelectPb")
	proto.RegisterType((*ContextPb)(nil), "plan.ContextPb")
	proto.RegisterType((*SourcePb)(nil), "plan.SourcePb")
	proto.RegisterType((*WherePb)(nil), "plan.WherePb")
	proto.RegisterType((*GroupByPb)(nil), "plan.GroupByPb")
	proto.RegisterType((*HavingPb)(nil), "plan.HavingPb")
	proto.RegisterType((*OrderPb)(nil), "plan.OrderPb")
	proto.RegisterType((*JoinMergePb)(nil), "plan.JoinMergePb")
	proto.RegisterType((*JoinKeyPb)(nil), "plan.JoinKeyPb")
}
func (m *PlanPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PlanPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SelectPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *SelectPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ContextPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ContextPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SourcePb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *SourcePb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *WherePb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *WherePb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *GroupByPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *GroupByPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *HavingPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *HavingPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *OrderPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *OrderPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *JoinMergePb) Marshal() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *JoinMergePb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *JoinKeyPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *JoinKeyPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func encodeFixed64Plan(data []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func encodeFixed32Plan(data []byte, offset int, v uint32) int { _ = "STUB: not implemented"; return 0 }

func encodeVarintPlan(data []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *PlanPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ContextPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SourcePb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WherePb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GroupByPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HavingPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *OrderPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *JoinMergePb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *JoinKeyPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPlan(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPlan(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SelectPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ContextPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SourcePb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WherePb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GroupByPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HavingPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *OrderPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *JoinMergePb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *JoinKeyPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func skipPlan(data []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPlan = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPlan   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorPlan = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x5b, 0x8e, 0xd3, 0x3c,
	0x18, 0x9d, 0xf4, 0x9a, 0x7c, 0xed, 0xff, 0x53, 0xc2, 0x08, 0x99, 0x79, 0x28, 0x55, 0xb8, 0xa8,
	0x30, 0x22, 0x11, 0x65, 0x07, 0x45, 0xc0, 0x68, 0x10, 0x43, 0xa5, 0x79, 0x40, 0xe2, 0x2d, 0x17,
	0x4f, 0x92, 0x91, 0x1b, 0xa7, 0x6e, 0x0a, 0x9d, 0x9d, 0xb0, 0x05, 0x76, 0xd2, 0x47, 0x56, 0x80,
	0xb8, 0x3c, 0xb0, 0x0d, 0x1c, 0x3b, 0x71, 0x5d, 0x24, 0x46, 0xe5, 0x21, 0x52, 0x72, 0x7c, 0x7c,
	0xfc, 0xf9, 0x3b, 0xe7, 0x0b, 0x40, 0x4e, 0xfc, 0xcc, 0xcd, 0x19, 0x2d, 0xa8, 0xdd, 0x2a, 0xdf,
	0x8f, 0x9e, 0xc4, 0x69, 0x91, 0xac, 0x02, 0x37, 0xa4, 0x73, 0x2f, 0xa6, 0x31, 0xf5, 0xc4, 0x62,
	0xb0, 0xba, 0x10, 0x5f, 0xe2, 0x43, 0xbc, 0xc9, 0x4d, 0x47, 0x8f, 0x34, 0xba, 0xcf, 0xfc, 0x28,
	0xa2, 0x99, 0xb7, 0x20, 0x01, 0x4b, 0xa3, 0x18, 0x7b, 0x0c, 0x13, 0x6f, 0xb9, 0x20, 0x15, 0xf5,
	0xf8, 0x3a, 0x2a, 0x5e, 0xe7, 0xcc, 0xcb, 0x68, 0x84, 0x25, 0xd9, 0xf9, 0xdc, 0x84, 0xce, 0x8c,
	0xd7, 0x33, 0x0b, 0xec, 0xdb, 0x60, 0xe6, 0x9c, 0x4f, 0x08, 0x26, 0xc8, 0x18, 0x35, 0xc6, 0xe6,
	0xb4, 0xb5, 0xf9, 0x7a, 0xf7, 0xc0, 0xbe, 0x0f, 0x9d, 0x25, 0x26, 0x38, 0x2c, 0x50, 0x73, 0x64,
	0x8c, 0x7b, 0x93, 0xff, 0x5d, 0x71, 0x99, 0x73, 0x81, 0xcd, 0x02, 0xc1, 0x32, 0x04, 0x8b, 0xae,
	0x58, 0x88, 0x51, 0x6b, 0x87, 0x25, 0x30, 0xc5, 0x72, 0xa0, 0xfd, 0x31, 0xc1, 0x0c, 0xa3, 0xb6,
	0x20, 0xfd, 0x27, 0x49, 0xef, 0x4a, 0x48, 0x57, 0x4a, 0xfc, 0x0f, 0x69, 0x16, 0xa3, 0x8e, 0xae,
	0x74, 0x22, 0x30, 0xc5, 0x7a, 0x08, 0xdd, 0x98, 0xd1, 0x55, 0x3e, 0xbd, 0x42, 0x5d, 0x41, 0xbb,
	0x21, 0x69, 0xaf, 0x24, 0xa8, 0x9f, 0x48, 0x59, 0x84, 0x19, 0x32, 0xf5, 0x13, 0xdf, 0x96, 0x90,
	0xe2, 0x3c, 0x06, 0xeb, 0x92, 0xa6, 0xd9, 0x1b, 0xcc, 0x62, 0x8c, 0x2c, 0xc1, 0xbb, 0x29, 0x79,
	0xa7, 0x35, 0xac, 0x9f, 0x5b, 0x72, 0x5f, 0xe3, 0x2b, 0x04, 0xfa, 0xb9, 0xa7, 0x12, 0x54, 0xbc,
	0x63, 0xee, 0x39, 0xa3, 0x97, 0xbc, 0x45, 0x29, 0xcd, 0x50, 0xaf, 0x12, 0xe5, 0x4e, 0xb9, 0x33,
	0x05, 0x6b, 0x57, 0x36, 0xc3, 0x24, 0x25, 0x11, 0xc3, 0x19, 0xea, 0x8f, 0x9a, 0x9c, 0xda, 0x97,
	0xaa, 0xd2, 0x1a, 0xc9, 0x72, 0xde, 0x83, 0x59, 0x37, 0x9d, 0x97, 0x51, 0x9b, 0x52, 0x5a, 0xd5,
	0x9b, 0x0c, 0x84, 0xf4, 0xf9, 0x82, 0xfc, 0x61, 0x0b, 0x2f, 0x37, 0xa4, 0x59, 0x81, 0xd7, 0x05,
	0x6a, 0xe8, 0xe5, 0x3e, 0x97, 0xa0, 0xd2, 0x3e, 0x03, 0x4b, 0x41, 0xf6, 0x21, 0x17, 0x0f, 0x13,
	0x3c, 0xf7, 0x85, 0xb8, 0x55, 0xe5, 0x60, 0x00, 0x8d, 0x34, 0xe2, 0x2a, 0x8d, 0x71, 0xab, 0x42,
	0xee, 0x40, 0xef, 0x82, 0x7b, 0x82, 0x59, 0xce, 0xd2, 0xac, 0x8c, 0x87, 0x5a, 0x72, 0x7e, 0x19,
	0xbc, 0xd8, 0xca, 0x7b, 0x7b, 0x08, 0x83, 0x0c, 0xe3, 0x68, 0x79, 0xe2, 0x2f, 0x13, 0x3f, 0x20,
	0xb8, 0x6c, 0x5e, 0x43, 0x4b, 0xd8, 0x2d, 0x68, 0x73, 0x1d, 0x9f, 0x08, 0x85, 0x1a, 0xe4, 0x71,
	0xe4, 0x09, 0xce, 0x09, 0x2e, 0xca, 0x48, 0x6d, 0x71, 0x1b, 0x5a, 0xa5, 0x01, 0x3c, 0x41, 0x5b,
	0x0c, 0x01, 0xc8, 0xf0, 0xbd, 0x58, 0xe3, 0x90, 0xc7, 0x66, 0xbb, 0xc2, 0xaf, 0x12, 0xae, 0x96,
	0x05, 0x9d, 0x8b, 0x94, 0xf4, 0xab, 0xae, 0xdc, 0x03, 0x8b, 0xcf, 0x8b, 0xac, 0xaf, 0x0a, 0xc6,
	0xb6, 0x81, 0x75, 0xd5, 0x0f, 0x76, 0x1c, 0xb4, 0xfe, 0xe2, 0xa0, 0xf3, 0x12, 0xba, 0x55, 0x7e,
	0x77, 0x4c, 0x31, 0xae, 0x31, 0x45, 0xdd, 0x57, 0x6b, 0x82, 0xf3, 0x0c, 0x2c, 0x95, 0xdd, 0x7d,
	0x95, 0x9c, 0x09, 0x98, 0xf5, 0x5c, 0xec, 0xbd, 0xe7, 0x29, 0x74, 0xab, 0xf8, 0xff, 0xc3, 0x96,
	0x9e, 0x36, 0x09, 0x7c, 0xa6, 0xea, 0x09, 0x95, 0xdb, 0xfa, 0x6e, 0xf9, 0x5b, 0x71, 0xcf, 0xf8,
	0x6f, 0x45, 0x6d, 0xf1, 0xc0, 0x52, 0x23, 0xb1, 0xcf, 0x86, 0xe9, 0xe1, 0xe6, 0xfb, 0xf0, 0x60,
	0xf3, 0x63, 0x68, 0x7c, 0xe1, 0xcf, 0x37, 0xfe, 0x7c, 0xfa, 0x39, 0x3c, 0xf8, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x08, 0xa3, 0x5b, 0x39, 0x05, 0x00, 0x00,
}
