// Code generated by protoc-gen-gogo.
// source: sql.proto
// DO NOT EDIT!

/*
Package rel is a generated protocol buffer package.

It is generated from these files:

	sql.proto

It has these top-level messages:

	SqlStatementPb
	SqlSelectPb
	SqlSourcePb
	SqlWherePb
	ProjectionPb
	ResultColumnPb
	KvInt
	ColumnPb
	CommandColumnPb
*/
package rel

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	expr "github.com/araddon/qlbridge/expr"

	_ "github.com/gogo/protobuf/gogoproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The generic SqlStatement, must be exactly one of these types
type SqlStatementPb struct {
	Select           *SqlSelectPb  `protobuf:"bytes,1,opt,name=select" json:"select,omitempty"`
	Source           *SqlSourcePb  `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Projection       *ProjectionPb `protobuf:"bytes,4,opt,name=projection" json:"projection,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SqlStatementPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SqlStatementPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*SqlStatementPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SqlStatementPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SqlStatementPb) GetSelect() *SqlSelectPb { _ = "STUB: not implemented"; return nil }

func (m *SqlStatementPb) GetSource() *SqlSourcePb { _ = "STUB: not implemented"; return nil }

func (m *SqlStatementPb) GetProjection() *ProjectionPb { _ = "STUB: not implemented"; return nil }

type SqlSelectPb struct {
	Db               string         `protobuf:"bytes,1,req,name=db" json:"db"`
	Raw              string         `protobuf:"bytes,2,req,name=raw" json:"raw"`
	Star             bool           `protobuf:"varint,3,req,name=star" json:"star"`
	Distinct         bool           `protobuf:"varint,4,req,name=distinct" json:"distinct"`
	Columns          []*ColumnPb    `protobuf:"bytes,5,rep,name=columns" json:"columns,omitempty"`
	From             []*SqlSourcePb `protobuf:"bytes,6,rep,name=from" json:"from,omitempty"`
	Into             *string        `protobuf:"bytes,7,opt,name=into" json:"into,omitempty"`
	Where            *SqlWherePb    `protobuf:"bytes,8,opt,name=where" json:"where,omitempty"`
	Having           *expr.NodePb   `protobuf:"bytes,9,opt,name=having" json:"having,omitempty"`
	GroupBy          []*ColumnPb    `protobuf:"bytes,11,rep,name=groupBy" json:"groupBy,omitempty"`
	OrderBy          []*ColumnPb    `protobuf:"bytes,10,rep,name=orderBy" json:"orderBy,omitempty"`
	Limit            int32          `protobuf:"varint,12,opt,name=limit" json:"limit"`
	Offset           int32          `protobuf:"varint,13,opt,name=offset" json:"offset"`
	Alias            *string        `protobuf:"bytes,14,opt,name=alias" json:"alias,omitempty"`
	Projection       *ProjectionPb  `protobuf:"bytes,15,opt,name=projection" json:"projection,omitempty"`
	IsAgg            bool           `protobuf:"varint,16,req,name=isAgg" json:"isAgg"`
	Finalized        bool           `protobuf:"varint,17,req,name=finalized" json:"finalized"`
	Schemaqry        bool           `protobuf:"varint,18,req,name=schemaqry" json:"schemaqry"`
	With             []byte         `protobuf:"bytes,19,opt,name=with" json:"with,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SqlSelectPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SqlSelectPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*SqlSelectPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SqlSelectPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SqlSelectPb) GetDb() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSelectPb) GetRaw() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSelectPb) GetStar() bool { _ = "STUB: not implemented"; return false }

func (m *SqlSelectPb) GetDistinct() bool { _ = "STUB: not implemented"; return false }

func (m *SqlSelectPb) GetColumns() []*ColumnPb { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) GetFrom() []*SqlSourcePb { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) GetInto() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSelectPb) GetWhere() *SqlWherePb { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) GetHaving() *expr.NodePb { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) GetGroupBy() []*ColumnPb { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) GetOrderBy() []*ColumnPb { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) GetLimit() int32 { _ = "STUB: not implemented"; return 0 }

func (m *SqlSelectPb) GetOffset() int32 { _ = "STUB: not implemented"; return 0 }

func (m *SqlSelectPb) GetAlias() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSelectPb) GetProjection() *ProjectionPb { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) GetIsAgg() bool { _ = "STUB: not implemented"; return false }

func (m *SqlSelectPb) GetFinalized() bool { _ = "STUB: not implemented"; return false }

func (m *SqlSelectPb) GetSchemaqry() bool { _ = "STUB: not implemented"; return false }

func (m *SqlSelectPb) GetWith() []byte { _ = "STUB: not implemented"; return nil }

type SqlSourcePb struct {
	Final            bool           `protobuf:"varint,1,opt,name=final" json:"final"`
	AliasInner       *string        `protobuf:"bytes,2,opt,name=aliasInner" json:"aliasInner,omitempty"`
	Columns          []*ColumnPb    `protobuf:"bytes,3,rep,name=columns" json:"columns,omitempty"`
	ColIndex         []KvInt        `protobuf:"bytes,4,rep,name=colIndex" json:"colIndex"`
	JoinNodes        []*expr.NodePb `protobuf:"bytes,5,rep,name=joinNodes" json:"joinNodes,omitempty"`
	Source           *SqlSelectPb   `protobuf:"bytes,6,opt,name=source" json:"source,omitempty"`
	Raw              string         `protobuf:"bytes,7,opt,name=raw" json:"raw"`
	Name             string         `protobuf:"bytes,8,opt,name=name" json:"name"`
	Alias            string         `protobuf:"bytes,9,opt,name=alias" json:"alias"`
	Op               int32          `protobuf:"varint,10,req,name=op" json:"op"`
	LeftOrRight      int32          `protobuf:"varint,11,req,name=leftOrRight" json:"leftOrRight"`
	JoinType         int32          `protobuf:"varint,12,req,name=joinType" json:"joinType"`
	JoinExpr         *expr.NodePb   `protobuf:"bytes,13,opt,name=joinExpr" json:"joinExpr,omitempty"`
	SubQuery         *SqlSelectPb   `protobuf:"bytes,14,opt,name=subQuery" json:"subQuery,omitempty"`
	Seekable         bool           `protobuf:"varint,15,opt,name=seekable" json:"seekable"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SqlSourcePb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SqlSourcePb) String() string            { _ = "STUB: not implemented"; return "" }
func (*SqlSourcePb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SqlSourcePb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SqlSourcePb) GetFinal() bool { _ = "STUB: not implemented"; return false }

func (m *SqlSourcePb) GetAliasInner() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSourcePb) GetColumns() []*ColumnPb { _ = "STUB: not implemented"; return nil }

func (m *SqlSourcePb) GetColIndex() []KvInt { _ = "STUB: not implemented"; return nil }

func (m *SqlSourcePb) GetJoinNodes() []*expr.NodePb { _ = "STUB: not implemented"; return nil }

func (m *SqlSourcePb) GetSource() *SqlSelectPb { _ = "STUB: not implemented"; return nil }

func (m *SqlSourcePb) GetRaw() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSourcePb) GetName() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSourcePb) GetAlias() string { _ = "STUB: not implemented"; return "" }

func (m *SqlSourcePb) GetOp() int32 { _ = "STUB: not implemented"; return 0 }

func (m *SqlSourcePb) GetLeftOrRight() int32 { _ = "STUB: not implemented"; return 0 }

func (m *SqlSourcePb) GetJoinType() int32 { _ = "STUB: not implemented"; return 0 }

func (m *SqlSourcePb) GetJoinExpr() *expr.NodePb { _ = "STUB: not implemented"; return nil }

func (m *SqlSourcePb) GetSubQuery() *SqlSelectPb { _ = "STUB: not implemented"; return nil }

func (m *SqlSourcePb) GetSeekable() bool { _ = "STUB: not implemented"; return false }

type SqlWherePb struct {
	Op               int32        `protobuf:"varint,1,req,name=op" json:"op"`
	Source           *SqlSelectPb `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Expr             *expr.NodePb `protobuf:"bytes,3,opt,name=Expr,json=expr" json:"Expr,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SqlWherePb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SqlWherePb) String() string            { _ = "STUB: not implemented"; return "" }
func (*SqlWherePb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SqlWherePb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SqlWherePb) GetOp() int32 { _ = "STUB: not implemented"; return 0 }

func (m *SqlWherePb) GetSource() *SqlSelectPb { _ = "STUB: not implemented"; return nil }

func (m *SqlWherePb) GetExpr() *expr.NodePb { _ = "STUB: not implemented"; return nil }

type ProjectionPb struct {
	Distinct         bool              `protobuf:"varint,1,req,name=distinct" json:"distinct"`
	Final            bool              `protobuf:"varint,2,req,name=final" json:"final"`
	ColNames         []string          `protobuf:"bytes,3,rep,name=colNames" json:"colNames,omitempty"`
	Columns          []*ResultColumnPb `protobuf:"bytes,4,rep,name=columns" json:"columns,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ProjectionPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProjectionPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProjectionPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProjectionPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProjectionPb) GetDistinct() bool { _ = "STUB: not implemented"; return false }

func (m *ProjectionPb) GetFinal() bool { _ = "STUB: not implemented"; return false }

func (m *ProjectionPb) GetColNames() []string { _ = "STUB: not implemented"; return nil }

func (m *ProjectionPb) GetColumns() []*ResultColumnPb { _ = "STUB: not implemented"; return nil }

type ResultColumnPb struct {
	Final            *bool     `protobuf:"varint,1,opt,name=final" json:"final,omitempty"`
	Name             string    `protobuf:"bytes,2,req,name=name" json:"name"`
	ColPos           int32     `protobuf:"varint,3,req,name=colPos" json:"colPos"`
	Column           *ColumnPb `protobuf:"bytes,4,opt,name=column" json:"column,omitempty"`
	Star             *bool     `protobuf:"varint,5,opt,name=star" json:"star,omitempty"`
	As               string    `protobuf:"bytes,6,req,name=as" json:"as"`
	ValueType        int32     `protobuf:"varint,7,req,name=valueType" json:"valueType"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ResultColumnPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ResultColumnPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*ResultColumnPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ResultColumnPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ResultColumnPb) GetFinal() bool { _ = "STUB: not implemented"; return false }

func (m *ResultColumnPb) GetName() string { _ = "STUB: not implemented"; return "" }

func (m *ResultColumnPb) GetColPos() int32 { _ = "STUB: not implemented"; return 0 }

func (m *ResultColumnPb) GetColumn() *ColumnPb { _ = "STUB: not implemented"; return nil }

func (m *ResultColumnPb) GetStar() bool { _ = "STUB: not implemented"; return false }

func (m *ResultColumnPb) GetAs() string { _ = "STUB: not implemented"; return "" }

func (m *ResultColumnPb) GetValueType() int32 { _ = "STUB: not implemented"; return 0 }

type KvInt struct {
	K                string `protobuf:"bytes,1,req,name=k" json:"k"`
	V                int32  `protobuf:"varint,2,req,name=v" json:"v"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KvInt) Reset()                    { _ = "STUB: not implemented"; return }
func (m *KvInt) String() string            { _ = "STUB: not implemented"; return "" }
func (*KvInt) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*KvInt) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *KvInt) GetK() string { _ = "STUB: not implemented"; return "" }

func (m *KvInt) GetV() int32 { _ = "STUB: not implemented"; return 0 }

type ColumnPb struct {
	SourceQuote      []byte       `protobuf:"bytes,1,opt,name=sourceQuote" json:"sourceQuote,omitempty"`
	AsQuoteByte      []byte       `protobuf:"bytes,2,opt,name=asQuoteByte" json:"asQuoteByte,omitempty"`
	OriginalAs       *string      `protobuf:"bytes,3,opt,name=originalAs" json:"originalAs,omitempty"`
	Left             *string      `protobuf:"bytes,4,opt,name=left" json:"left,omitempty"`
	Right            *string      `protobuf:"bytes,5,opt,name=right" json:"right,omitempty"`
	ParentIndex      int32        `protobuf:"varint,6,opt,name=parentIndex" json:"parentIndex"`
	Index            int32        `protobuf:"varint,7,opt,name=index" json:"index"`
	SourceIndex      int32        `protobuf:"varint,8,opt,name=sourceIndex" json:"sourceIndex"`
	SourceField      *string      `protobuf:"bytes,9,opt,name=sourceField" json:"sourceField,omitempty"`
	As               string       `protobuf:"bytes,11,opt,name=as" json:"as"`
	Comment          *string      `protobuf:"bytes,12,opt,name=comment" json:"comment,omitempty"`
	Order            *string      `protobuf:"bytes,13,opt,name=order" json:"order,omitempty"`
	Star             *bool        `protobuf:"varint,14,opt,name=star" json:"star,omitempty"`
	Agg              bool         `protobuf:"varint,15,opt,name=agg" json:"agg"`
	Expr             *expr.NodePb `protobuf:"bytes,16,opt,name=Expr,json=expr" json:"Expr,omitempty"`
	Guard            *expr.NodePb `protobuf:"bytes,17,opt,name=Guard,json=guard" json:"Guard,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ColumnPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ColumnPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*ColumnPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ColumnPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ColumnPb) GetSourceQuote() []byte { _ = "STUB: not implemented"; return nil }

func (m *ColumnPb) GetAsQuoteByte() []byte { _ = "STUB: not implemented"; return nil }

func (m *ColumnPb) GetOriginalAs() string { _ = "STUB: not implemented"; return "" }

func (m *ColumnPb) GetLeft() string { _ = "STUB: not implemented"; return "" }

func (m *ColumnPb) GetRight() string { _ = "STUB: not implemented"; return "" }

func (m *ColumnPb) GetParentIndex() int32 { _ = "STUB: not implemented"; return 0 }

func (m *ColumnPb) GetIndex() int32 { _ = "STUB: not implemented"; return 0 }

func (m *ColumnPb) GetSourceIndex() int32 { _ = "STUB: not implemented"; return 0 }

func (m *ColumnPb) GetSourceField() string { _ = "STUB: not implemented"; return "" }

func (m *ColumnPb) GetAs() string { _ = "STUB: not implemented"; return "" }

func (m *ColumnPb) GetComment() string { _ = "STUB: not implemented"; return "" }

func (m *ColumnPb) GetOrder() string { _ = "STUB: not implemented"; return "" }

func (m *ColumnPb) GetStar() bool { _ = "STUB: not implemented"; return false }

func (m *ColumnPb) GetAgg() bool { _ = "STUB: not implemented"; return false }

func (m *ColumnPb) GetExpr() *expr.NodePb { _ = "STUB: not implemented"; return nil }

func (m *ColumnPb) GetGuard() *expr.NodePb { _ = "STUB: not implemented"; return nil }

type CommandColumnPb struct {
	Expr             *expr.NodePb `protobuf:"bytes,1,opt,name=Expr,json=expr" json:"Expr,omitempty"`
	Name             string       `protobuf:"bytes,2,req,name=name" json:"name"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CommandColumnPb) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CommandColumnPb) String() string            { _ = "STUB: not implemented"; return "" }
func (*CommandColumnPb) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CommandColumnPb) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommandColumnPb) GetExpr() *expr.NodePb { _ = "STUB: not implemented"; return nil }

func (m *CommandColumnPb) GetName() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*SqlStatementPb)(nil), "rel.SqlStatementPb")
	proto.RegisterType((*SqlSelectPb)(nil), "rel.SqlSelectPb")
	proto.RegisterType((*SqlSourcePb)(nil), "rel.SqlSourcePb")
	proto.RegisterType((*SqlWherePb)(nil), "rel.SqlWherePb")
	proto.RegisterType((*ProjectionPb)(nil), "rel.ProjectionPb")
	proto.RegisterType((*ResultColumnPb)(nil), "rel.ResultColumnPb")
	proto.RegisterType((*KvInt)(nil), "rel.KvInt")
	proto.RegisterType((*ColumnPb)(nil), "rel.ColumnPb")
	proto.RegisterType((*CommandColumnPb)(nil), "rel.CommandColumnPb")
}
func (m *SqlStatementPb) Marshal() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SqlStatementPb) MarshalTo(data []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SqlSelectPb) Marshal() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SqlSelectPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SqlSourcePb) Marshal() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SqlSourcePb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SqlWherePb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *SqlWherePb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ProjectionPb) Marshal() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProjectionPb) MarshalTo(data []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResultColumnPb) Marshal() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResultColumnPb) MarshalTo(data []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *KvInt) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *KvInt) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ColumnPb) Marshal() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ColumnPb) MarshalTo(data []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *CommandColumnPb) Marshal() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CommandColumnPb) MarshalTo(data []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeFixed64Sql(data []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func encodeFixed32Sql(data []byte, offset int, v uint32) int { _ = "STUB: not implemented"; return 0 }

func encodeVarintSql(data []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *SqlStatementPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SqlSelectPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SqlSourcePb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SqlWherePb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProjectionPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ResultColumnPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *KvInt) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ColumnPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommandColumnPb) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovSql(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozSql(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SqlStatementPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SqlSelectPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SqlSourcePb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SqlWherePb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProjectionPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ResultColumnPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *KvInt) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ColumnPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommandColumnPb) Unmarshal(data []byte) error { _ = "STUB: not implemented"; return nil }

func skipSql(data []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthSql = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSql   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorSql = []byte{
	// 1067 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0x25, 0x51, 0x96, 0x56, 0x8e, 0xed, 0x6c, 0x82, 0x62, 0x61, 0x14, 0xae, 0x41, 0x14,
	0x81, 0xd1, 0x34, 0x52, 0x91, 0x1e, 0x7a, 0x8e, 0x83, 0xb6, 0x30, 0x0a, 0xa4, 0x8e, 0x5c, 0xa0,
	0x67, 0x4a, 0x5c, 0x51, 0x8c, 0x29, 0xae, 0xbc, 0x24, 0xe5, 0x38, 0x4f, 0xd2, 0x4b, 0x81, 0x5e,
	0x7b, 0xeb, 0x33, 0xf4, 0xe4, 0x63, 0x9f, 0xa0, 0xe8, 0x0f, 0xfa, 0x1e, 0x9d, 0x99, 0x25, 0x97,
	0x6b, 0x47, 0x72, 0x72, 0x10, 0xc0, 0xfd, 0xe6, 0xdb, 0xdd, 0x99, 0xd9, 0x6f, 0x66, 0xc4, 0xfa,
	0xf9, 0x45, 0x3a, 0x5c, 0x6a, 0x55, 0x28, 0xde, 0xd6, 0x32, 0xdd, 0x7f, 0x12, 0x27, 0xc5, 0xbc,
	0x9c, 0x0c, 0xa7, 0x6a, 0x31, 0x0a, 0x75, 0x18, 0x45, 0x2a, 0x1b, 0x5d, 0xa4, 0x13, 0x9d, 0x44,
	0xb1, 0x1c, 0xc9, 0x37, 0x4b, 0x3d, 0xca, 0x54, 0x24, 0xcd, 0x8e, 0xfd, 0xa7, 0x0e, 0x39, 0x56,
	0xb1, 0x1a, 0x11, 0x3c, 0x29, 0x67, 0xb4, 0xa2, 0x05, 0x7d, 0x19, 0x7a, 0xf0, 0xab, 0xc7, 0x76,
	0xce, 0x2e, 0xd2, 0xb3, 0x22, 0x2c, 0xe4, 0x42, 0x66, 0xc5, 0xe9, 0x84, 0x0f, 0x59, 0x37, 0x97,
	0xa9, 0x9c, 0x16, 0xc2, 0x3b, 0xf4, 0x8e, 0x06, 0xcf, 0xf6, 0x86, 0xe0, 0xc4, 0x10, 0x49, 0x84,
	0x9e, 0x4e, 0x8e, 0x3b, 0xd7, 0x7f, 0x7e, 0xe2, 0x8d, 0x2b, 0x16, 0xf1, 0x55, 0xa9, 0xa7, 0x52,
	0xb4, 0x6e, 0xf1, 0x09, 0x75, 0xf8, 0xb4, 0xe6, 0x5f, 0x31, 0x06, 0x77, 0xbf, 0x86, 0xad, 0x89,
	0xca, 0x44, 0x87, 0xf6, 0x3c, 0xa0, 0x3d, 0xa7, 0x16, 0xb6, 0x9b, 0x1c, 0x6a, 0xf0, 0x9b, 0xcf,
	0x06, 0x8e, 0x1b, 0xfc, 0x11, 0x6b, 0x45, 0x13, 0x70, 0xb2, 0x75, 0xd4, 0x27, 0xf6, 0xbd, 0x31,
	0xac, 0xf9, 0x47, 0xac, 0xad, 0xc3, 0x4b, 0xf0, 0xa5, 0x81, 0x11, 0xe0, 0x82, 0x75, 0xf2, 0x22,
	0xd4, 0xa2, 0x0d, 0x86, 0x5e, 0x65, 0x20, 0x84, 0x1f, 0xb2, 0x5e, 0x94, 0xe4, 0x45, 0x92, 0x41,
	0xc8, 0x1d, 0xc7, 0x6a, 0x51, 0xfe, 0x94, 0x6d, 0x4d, 0x55, 0x5a, 0x2e, 0xb2, 0x5c, 0xf8, 0x87,
	0x6d, 0xf0, 0xf7, 0x3e, 0xf9, 0xfb, 0x82, 0x30, 0xeb, 0x6b, 0xcd, 0xe1, 0x9f, 0xb1, 0xce, 0x4c,
	0xab, 0x85, 0xe8, 0x12, 0x77, 0x53, 0x3e, 0x88, 0x83, 0x6e, 0x25, 0x59, 0xa1, 0xc4, 0x16, 0xe4,
	0xa1, 0x5f, 0x5b, 0x10, 0xe1, 0x4f, 0x98, 0x7f, 0x39, 0x97, 0x5a, 0x8a, 0x1e, 0xa5, 0x68, 0xb7,
	0x3e, 0xe6, 0x47, 0x04, 0xed, 0x29, 0x86, 0x03, 0x57, 0x76, 0xe7, 0xe1, 0x2a, 0xc9, 0x62, 0xd1,
	0x27, 0xf6, 0xf6, 0x10, 0x85, 0x31, 0x7c, 0x09, 0xc2, 0x68, 0x1e, 0xc0, 0x30, 0x30, 0x1a, 0xa5,
	0x23, 0xa9, 0x8f, 0xaf, 0x04, 0xbb, 0x23, 0x9a, 0x8a, 0x83, 0xf4, 0x58, 0xab, 0x72, 0x09, 0xf4,
	0xc1, 0x1d, 0xf4, 0x8a, 0xc3, 0xf7, 0x99, 0x9f, 0x26, 0x8b, 0xa4, 0x10, 0xdb, 0xe0, 0x88, 0x5f,
	0xa5, 0xd2, 0x40, 0xfc, 0x63, 0xd6, 0x55, 0xb3, 0x59, 0x2e, 0x0b, 0x71, 0xdf, 0x31, 0x56, 0x18,
	0xee, 0x0c, 0xd3, 0x24, 0xcc, 0xc5, 0x8e, 0x93, 0x0b, 0x03, 0xdd, 0x12, 0xcd, 0xee, 0x07, 0x8b,
	0x06, 0x0f, 0x4d, 0xf2, 0xe7, 0x71, 0x2c, 0xf6, 0x9c, 0x97, 0x35, 0x10, 0x0f, 0x58, 0x7f, 0x96,
	0x64, 0x70, 0xc1, 0x5b, 0x19, 0x89, 0x07, 0x8e, 0xbd, 0x81, 0x91, 0x93, 0x4f, 0xe7, 0x72, 0x11,
	0x5e, 0xe8, 0x2b, 0xc1, 0x5d, 0x8e, 0x85, 0xf1, 0x0d, 0x2f, 0xa1, 0xea, 0xc4, 0x43, 0x70, 0x6b,
	0xbb, 0x7e, 0x43, 0x44, 0x82, 0xdf, 0x3b, 0x46, 0xb2, 0xd5, 0xcb, 0xa3, 0x37, 0x74, 0x34, 0x95,
	0x96, 0xf5, 0x86, 0x20, 0xfe, 0x29, 0x63, 0x14, 0xeb, 0x49, 0x96, 0x49, 0x4d, 0xb5, 0x54, 0xe7,
	0xc0, 0xc1, 0x5d, 0x29, 0xb6, 0x3f, 0x40, 0x8a, 0x9f, 0xb3, 0x1e, 0x7c, 0x9e, 0x64, 0x91, 0x7c,
	0x03, 0xda, 0x46, 0x3e, 0x23, 0xfe, 0x77, 0xab, 0x93, 0xac, 0xa8, 0x75, 0x5e, 0x33, 0xf8, 0x17,
	0xac, 0xff, 0x5a, 0x25, 0x19, 0xaa, 0xa6, 0x56, 0xfa, 0x3a, 0x21, 0x35, 0x24, 0xa7, 0xf8, 0xbb,
	0xef, 0x69, 0x16, 0xa6, 0xf8, 0xab, 0xea, 0x6c, 0xd4, 0xde, 0x54, 0x67, 0x16, 0x2e, 0x8c, 0xd6,
	0x6b, 0x03, 0x21, 0x8d, 0x2a, 0xfa, 0x8e, 0xa9, 0x52, 0x05, 0x74, 0x00, 0xb5, 0x04, 0x11, 0xb7,
	0xac, 0x96, 0x60, 0xcd, 0x1f, 0xb3, 0x41, 0x2a, 0x67, 0xc5, 0xf7, 0x7a, 0x9c, 0xc4, 0xf3, 0x02,
	0x44, 0xdb, 0x98, 0x5d, 0x03, 0xd6, 0x3d, 0x06, 0xf2, 0xc3, 0xd5, 0x52, 0x82, 0x58, 0x1b, 0x92,
	0x45, 0x21, 0x3a, 0xfa, 0xfe, 0x1a, 0x32, 0x40, 0x8a, 0x5d, 0x9f, 0x0e, 0xcb, 0xe1, 0xcf, 0x58,
	0x2f, 0x2f, 0x27, 0xaf, 0x4a, 0x09, 0x5a, 0xd9, 0xb9, 0x33, 0x1f, 0x96, 0x87, 0x5e, 0xe4, 0x52,
	0x9e, 0x87, 0x93, 0x54, 0x92, 0xae, 0x6d, 0xf7, 0xa9, 0xd1, 0xe0, 0x2d, 0x63, 0x4d, 0xd9, 0x57,
	0x31, 0x7b, 0xb7, 0x62, 0xde, 0xdc, 0x84, 0xd7, 0xbf, 0xc3, 0x63, 0xd6, 0xa1, 0xa8, 0xda, 0x1b,
	0xa3, 0xea, 0x20, 0x14, 0xfc, 0xec, 0xb1, 0x6d, 0xb7, 0xc2, 0x6e, 0x34, 0x4b, 0x6f, 0x6d, 0xb3,
	0xb4, 0x1a, 0x6f, 0xb9, 0x15, 0x67, 0x34, 0xbe, 0x4f, 0x72, 0x7c, 0x09, 0xef, 0x6a, 0xe4, 0xdb,
	0x1f, 0xdb, 0x35, 0xff, 0xb2, 0x51, 0xb6, 0x51, 0xea, 0x43, 0x8a, 0x61, 0x2c, 0xf3, 0x32, 0x2d,
	0x36, 0xe8, 0x3b, 0xf8, 0x0f, 0xe6, 0xd7, 0x4d, 0xc6, 0xba, 0x1a, 0xf3, 0xea, 0xfb, 0x6b, 0x99,
	0xb9, 0xd3, 0xc1, 0xc8, 0x0c, 0x5a, 0x13, 0x9c, 0x79, 0xaa, 0x72, 0x1a, 0x10, 0xb6, 0x35, 0x19,
	0x0c, 0x7a, 0x71, 0xd7, 0xdc, 0x58, 0xcd, 0xab, 0xb5, 0x45, 0x57, 0x51, 0xec, 0xa4, 0xf1, 0x9d,
	0xfb, 0xcd, 0xa4, 0x81, 0xb7, 0x03, 0x21, 0x77, 0xdd, 0x89, 0x05, 0x2a, 0x86, 0x16, 0xb3, 0x0a,
	0xd3, 0x52, 0x92, 0x10, 0xb7, 0x9c, 0xdb, 0x1b, 0x38, 0x18, 0x31, 0x9f, 0x4a, 0x96, 0x73, 0xe6,
	0x9d, 0xdf, 0x98, 0x79, 0xde, 0x39, 0x62, 0x2b, 0x0a, 0xa9, 0xde, 0xe8, 0xad, 0x82, 0x5f, 0x3a,
	0xac, 0x67, 0x53, 0x02, 0x15, 0x61, 0xde, 0xfd, 0x55, 0xa9, 0x0a, 0x49, 0x89, 0xa9, 0xfb, 0x94,
	0x6b, 0x40, 0x5e, 0x98, 0xd3, 0xe7, 0xf1, 0x55, 0x61, 0xa4, 0x64, 0x79, 0x8e, 0x01, 0x5b, 0x95,
	0xd2, 0x49, 0x8c, 0x29, 0x7d, 0x9e, 0x93, 0x86, 0x6c, 0xab, 0x6a, 0x70, 0xcc, 0x03, 0x96, 0x1b,
	0xa5, 0xcc, 0x8e, 0x36, 0x44, 0xf0, 0x89, 0x34, 0xd5, 0xa6, 0xef, 0x76, 0x7a, 0x82, 0xd0, 0x87,
	0x65, 0xa8, 0xe1, 0xaf, 0x88, 0x69, 0x5a, 0x5d, 0x67, 0x50, 0xb8, 0x06, 0x6a, 0xec, 0xc4, 0xd8,
	0x72, 0xe7, 0x0c, 0x41, 0x4d, 0xbc, 0xe6, 0x8c, 0x9e, 0x7b, 0x86, 0x63, 0x68, 0x78, 0xdf, 0x24,
	0x32, 0x8d, 0x9c, 0x0e, 0x63, 0xf3, 0x42, 0x86, 0xea, 0xdd, 0x06, 0x4e, 0x03, 0xc2, 0x77, 0x3b,
	0x40, 0xc1, 0x2e, 0xf0, 0x5f, 0x13, 0xcd, 0xba, 0x7e, 0xa3, 0x4d, 0x02, 0xd1, 0x43, 0x9a, 0xa1,
	0xd4, 0x3a, 0x6c, 0x94, 0x04, 0x59, 0x8d, 0xec, 0xbc, 0xa3, 0x11, 0xe8, 0x90, 0x21, 0x8c, 0x2b,
	0xb7, 0x15, 0x20, 0x60, 0x2b, 0x76, 0xef, 0xee, 0x8a, 0xe5, 0x47, 0xcc, 0xff, 0xb6, 0x0c, 0x35,
	0x0e, 0xb4, 0x4d, 0x44, 0x3f, 0x46, 0x42, 0x70, 0xc6, 0x76, 0x5f, 0x80, 0xab, 0x61, 0x16, 0x39,
	0x42, 0x31, 0x97, 0x78, 0xef, 0xb9, 0x64, 0x63, 0x1d, 0x1d, 0x3f, 0xba, 0xfe, 0xfb, 0xc0, 0xbb,
	0xfe, 0xe7, 0xc0, 0xfb, 0x03, 0x7e, 0x7f, 0xc1, 0xef, 0xa7, 0x7f, 0x0f, 0xee, 0xfd, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0x40, 0xb5, 0x23, 0xd3, 0x0a, 0x00, 0x00,
}
